;(() => {
  const atlas = (window.__nutriworkAtlasEngine = window.__nutriworkAtlasEngine || {})

  const templates = [
    {
      id: "open-1",
      kind: "open",
      title: "Primeiro passo",
      description: "Abra 1 conceito diferente do Atlas.",
      target: 1,
    },
    {
      id: "open-2",
      kind: "open",
      title: "Abra caminhos",
      description: "Explore 2 conceitos diferentes do Atlas.",
      target: 2,
    },
    {
      id: "open-3",
      kind: "open",
      title: "Pequena expedição",
      description: "Explore 3 conceitos diferentes do Atlas.",
      target: 3,
    },
    {
      id: "open-4",
      kind: "open",
      title: "Rota de estudo",
      description: "Explore 4 conceitos diferentes do Atlas.",
      target: 4,
    },
    {
      id: "open-5",
      kind: "open",
      title: "Grande travessia",
      description: "Explore 5 conceitos diferentes do Atlas.",
      target: 5,
    },
    {
      id: "open-6",
      kind: "open",
      title: "Mapa em movimento",
      description: "Abra 2 conceitos diferentes e continue explorando o Atlas.",
      target: 2,
    },
    {
      id: "open-7",
      kind: "open",
      title: "Olhar panorâmico",
      description: "Abra 3 conceitos diferentes em uma mesma sessão.",
      target: 3,
    },
    {
      id: "open-8",
      kind: "open",
      title: "Horizonte aberto",
      description: "Abra 4 conceitos diferentes para ampliar seu mapa.",
      target: 4,
    },
    {
      id: "discover-1",
      kind: "discover",
      title: "Descubra algo novo",
      description: "Abra 1 conceito que você ainda não visitou.",
      target: 1,
    },
    {
      id: "discover-2",
      kind: "discover",
      title: "Amplie o mapa",
      description: "Abra 2 conceitos que você ainda não visitou.",
      target: 2,
    },
    {
      id: "discover-3",
      kind: "discover",
      title: "Território inédito",
      description: "Abra 3 conceitos que você ainda não visitou.",
      target: 3,
    },
    {
      id: "discover-4",
      kind: "discover",
      title: "Nova constelação",
      description: "Abra 4 conceitos que você ainda não visitou.",
      target: 4,
    },
    {
      id: "discover-5",
      kind: "discover",
      title: "Expedição desconhecida",
      description: "Abra 5 conceitos que você ainda não visitou.",
      target: 5,
    },
    {
      id: "discover-6",
      kind: "discover",
      title: "Fora da rota",
      description: "Encontre 2 conceitos inéditos para você.",
      target: 2,
    },
    {
      id: "discover-7",
      kind: "discover",
      title: "Ponto não explorado",
      description: "Encontre 3 conceitos inéditos para você.",
      target: 3,
    },
    {
      id: "discover-8",
      kind: "discover",
      title: "Cartografia nova",
      description: "Encontre 4 conceitos inéditos para você.",
      target: 4,
    },
    {
      id: "revisit-1",
      kind: "revisit",
      title: "Retome uma ideia",
      description: "Revisite 1 conceito que você já viu.",
      target: 1,
    },
    {
      id: "revisit-2",
      kind: "revisit",
      title: "Reative conexões",
      description: "Revisite 2 conceitos que você já viu.",
      target: 2,
    },
    {
      id: "revisit-3",
      kind: "revisit",
      title: "Volte ao essencial",
      description: "Revisite 3 conceitos que você já viu.",
      target: 3,
    },
    {
      id: "revisit-4",
      kind: "revisit",
      title: "Memória de longo prazo",
      description: "Revisite 4 conceitos que você já viu.",
      target: 4,
    },
    {
      id: "revisit-5",
      kind: "revisit",
      title: "Revisão profunda",
      description: "Revisite 5 conceitos que você já viu.",
      target: 5,
    },
    {
      id: "revisit-6",
      kind: "revisit",
      title: "Caminho conhecido",
      description: "Retorne a 2 conceitos familiares.",
      target: 2,
    },
    {
      id: "revisit-7",
      kind: "revisit",
      title: "Pontos de referência",
      description: "Retorne a 3 conceitos familiares.",
      target: 3,
    },
    {
      id: "revisit-8",
      kind: "revisit",
      title: "Releitura conectada",
      description: "Retorne a 4 conceitos familiares.",
      target: 4,
    },
    {
      id: "graph-1",
      kind: "source",
      source: "graph",
      title: "Escolha um caminho",
      description: "Abra 1 nó diretamente pelo grafo.",
      target: 1,
    },
    {
      id: "graph-2",
      kind: "source",
      source: "graph",
      title: "Siga pelo grafo",
      description: "Abra 2 nós diretamente pelo grafo.",
      target: 2,
    },
    {
      id: "graph-3",
      kind: "source",
      source: "graph",
      title: "Trilha visual",
      description: "Abra 3 nós diretamente pelo grafo.",
      target: 3,
    },
    {
      id: "graph-4",
      kind: "source",
      source: "graph",
      title: "Navegação radial",
      description: "Abra 4 nós diretamente pelo grafo.",
      target: 4,
    },
    {
      id: "graph-5",
      kind: "source",
      source: "graph",
      title: "Rede em expansão",
      description: "Abra 5 nós diretamente pelo grafo.",
      target: 5,
    },
    {
      id: "graph-6",
      kind: "source",
      source: "graph",
      title: "Olhe ao redor",
      description: "Abra 2 nós próximos pelo grafo.",
      target: 2,
    },
    {
      id: "graph-7",
      kind: "source",
      source: "graph",
      title: "Mude de direção",
      description: "Abra 3 nós por caminhos diferentes do grafo.",
      target: 3,
    },
    {
      id: "graph-8",
      kind: "source",
      source: "graph",
      title: "Percorra a rede",
      description: "Abra 4 nós seguindo as relações do grafo.",
      target: 4,
    },
    {
      id: "connected-1",
      kind: "connected",
      title: "Uma ponte",
      description: "Abra 1 conceito conectado a outro que você visitou.",
      target: 1,
    },
    {
      id: "connected-2",
      kind: "connected",
      title: "Explore uma vizinhança",
      description: "Abra 2 conceitos conectados entre si.",
      target: 2,
    },
    {
      id: "connected-3",
      kind: "connected",
      title: "Percorra uma trilha",
      description: "Abra 3 conceitos conectados entre si.",
      target: 3,
    },
    {
      id: "connected-4",
      kind: "connected",
      title: "Atravesse a rede",
      description: "Abra 4 conceitos conectados em sequência.",
      target: 4,
    },
    {
      id: "connected-5",
      kind: "connected",
      title: "Rota de relações",
      description: "Abra 5 conceitos conectados em sequência.",
      target: 5,
    },
    {
      id: "connected-6",
      kind: "connected",
      title: "Vizinhos do mapa",
      description: "Encontre 2 conceitos ligados por relações diretas.",
      target: 2,
    },
    {
      id: "search-1",
      kind: "source",
      source: "search",
      title: "Use a busca",
      description: "Busque um conceito e abra um resultado.",
      target: 1,
    },
    {
      id: "search-2",
      kind: "source",
      source: "search",
      title: "Pesquise uma ideia",
      description: "Use a busca para abrir 2 resultados.",
      target: 2,
    },
    {
      id: "search-3",
      kind: "source",
      source: "search",
      title: "Busca comparativa",
      description: "Busque e abra 3 resultados diferentes.",
      target: 3,
    },
    {
      id: "search-4",
      kind: "source",
      source: "search",
      title: "Rota pela busca",
      description: "Use a busca para abrir 4 resultados diferentes.",
      target: 4,
    },
    {
      id: "search-5",
      kind: "source",
      source: "search",
      title: "Índice explorado",
      description: "Use a busca para abrir 5 resultados diferentes.",
      target: 5,
    },
    {
      id: "search-6",
      kind: "source",
      source: "search",
      title: "Encontre uma conexão",
      description: "Pesquise e abra 2 conceitos relacionados.",
      target: 2,
    },
    {
      id: "specific-1",
      kind: "specific",
      title: "Encontre um conceito",
      description: "Visite o conceito indicado no Atlas.",
      target: 1,
    },
    {
      id: "specific-2",
      kind: "specific",
      title: "Alvo do dia",
      description: "Abra a nota escolhida especialmente para hoje.",
      target: 1,
    },
    {
      id: "specific-3",
      kind: "specific",
      title: "Ponto de encontro",
      description: "Localize e visite o conceito indicado.",
      target: 1,
    },
    {
      id: "specific-4",
      kind: "specific",
      title: "Uma parada precisa",
      description: "Visite exatamente o conceito indicado no Atlas.",
      target: 1,
    },
    {
      id: "specific-5",
      kind: "specific",
      title: "Destino de estudo",
      description: "Chegue ao conceito escolhido para sua exploração.",
      target: 1,
    },
    {
      id: "specific-6",
      kind: "specific",
      title: "Nota em foco",
      description: "Abra a nota que o Atlas reservou para hoje.",
      target: 1,
    },
  ]

  atlas.dailyTaskTemplates = templates
})()
